# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'YardSail' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YardSail
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'FSCalendar'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'

  target 'YardSailTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YardSailUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
